### ISSUE TITLE
Proceso y ciclo de vida de un software

### ISSUE THREAD

**Issue by NicolasMattos03** [NicolasMattos03/RepositorioTSDWAD2022#3]
Coloquen el concepto de Ciclo de vida de un soft y el proceso para el desarrollo del mismo.

**Comment by josemaria-s** [comment]
El proceso de desarrollo (o ciclo de vida del software), que a priori podría parecer una tarea simple, consta de una serie de pasos de obligado cumplimiento que buscan garantizar que los programas creados son eficientes, fiables, seguros y responden a las necesidades de los usuarios finales
Fuente: https://intelequia.com/blog/post/2083/ciclo-de-vida-del-software-todo-lo-que-necesitas-saber#:~:text=El%20proceso%20de%20desarrollo%20(o,necesidades%20de%20los%20usuarios%20finales.
