### ISSUE TITLE
Agilidad y manifiesto agile

### ISSUE THREAD

**Issue by NicolasMattos03** [NicolasMattos03/RepositorioTSDWAD2022#4]
Colocar concepto de Agilidad y de manifiesto agile

**Comment by csobrero874** [comment]
La agilidad, relacionada con proyectos, está basada en ideologías que permiten la adaptación de los principios que guían el desarrollo de los mismos, adaptándolos continuamente a la evolución y mejora de ellos. El Manifiesto Agile está compuesto por los valores que guían la colaboración, la respuesta ante los cambios constantes, la atención y colaboración de los clientes, los individuos por encima del proceso y el software antes que la documentación exhaustiva.

**Comment by NicolasMattos03** [comment]
> La agilidad, relacionada con proyectos, está basada en ideologías que permiten la adaptación de los principios que guían el desarrollo de los mismos, adaptándolos continuamente a la evolución y mejora de ellos. El Manifiesto Agile está compuesto por los valores que guían la colaboración, la respuesta ante los cambios constantes, la atención y colaboración de los clientes, los individuos por encima del proceso y el software antes que la documentación exhaustiva.

Hola, esto debe ir dentro del archivo ConceptosScrum no aca en comentarios.!
