### ISSUE TITLE
Ceremonias, artefactos y roles

### ISSUE THREAD

**Issue by NicolasMattos03** [NicolasMattos03/RepositorioTSDWAD2022#6]
Colocar conceptos de estos 3 terminos

**Comment by nahuonaindia** [comment]
CEREMONIAS, ARTEFACTOS Y ROLES

CEREMONIAS:
Serie de reuniones en grupo que se realizan a lo largo del proyecto para llevar un control de trabajo

. Sprint Planning Meeting
. Daily Scrum Meeting
. Sprint Review Meeting
. Sprint Retrospective Meeting
----------------------------------------
SPRINT PLANNING MEETING
Reunión de planificación del sprint. Al iniciar cada Sprint, se realiza esta reunion con el objetivo de tomar decisiónes de que se hará en dicho Sprint. 

PLANIFICACION: ¿QUE HAY QUE CONSEGUIR?

1. Formar equipos (teniendo en cuenta diferencias de nivel, habilidad y genero)
2. Escoger el tema que queremos trabajar
3. Priorizar los temas que se van a trabajar primero, en que orden y porque

**Comment by NicolasMattos03** [comment]
> 

Hola, esto no va como comentario, va adentro del archivo README que ahora se llama ConceptosScrum, pero que ahora no aparece nose por que
